#include "c_codegen.h"
#include <stdio.h>
#include <string.h>
#include <stdarg.h>

// C Code Generator Implementation (Simplified)

CCodeGen* c_codegen_create(Arena* arena) {
    CCodeGen* gen = arena_alloc(arena, sizeof(CCodeGen));
    gen->arena = arena;
    gen->output = dyn_array_create(sizeof(char));
    gen->indent_level = 0;
    gen->label_counter = 0;
    gen->variables = hashmap_create(arena, 256);
    gen->used_builtins = hashmap_create(arena, 32);
    gen->uses_strings = false;
    gen->uses_arrays = false;
    gen->uses_structs = false;
    gen->uses_floats = false;
    return gen;
}

static void write_str(DynamicArray* output, const char* str) {
    while (*str) {
        dyn_array_append(output, (void*)str);
        str++;
    }
}

const char* c_codegen_generate(CCodeGen* gen, IRProgram* program) {
    // Simplified implementation - generates minimal C code
    write_str(gen->output, "// Generated by Elba C Code Generator\n");
    write_str(gen->output, "#include <stdio.h>\n");
    write_str(gen->output, "#include <stdlib.h>\n\n");
    write_str(gen->output, "int main(void) {\n");
    write_str(gen->output, "    printf(\"C codegen: work in progress\\n\");\n");
    write_str(gen->output, "    return 0;\n");
    write_str(gen->output, "}\n");
    
    // Null-terminate
    char null_term = '\0';
    dyn_array_append(gen->output, &null_term);
    
    return (const char*)gen->output->items;
}

bool c_codegen_write_file(CCodeGen* gen, const char* output_path) {
    FILE* f = fopen(output_path, "w");
    if (!f) {
        fprintf(stderr, "Failed to open output file: %s\n", output_path);
        return false;
    }
    
    fprintf(f, "%s", (const char*)gen->output->items);
    fclose(f);
    return true;
}

void c_codegen_free(CCodeGen* gen) {
    // Memory managed by arena
}
